//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
namespace AssemblyCSharp
{
	public class bluePrint
	{
		public string[] chromosomes{ get; set; }
		public string ID { get; set; }
		public GameObject instantiation{ get; set; }
		public float score{ get; set; }
		public float normalScore{ get; set; }
		public float startLocation { get; set; }
		public float endLocation { get; set; }
		public Transform trackerObject{ get; set; }
		public ArrayList unitArray { get; set; }
	

		public bluePrint(string ident, string[] chromes, GameObject parent)
		{
			score = 0;
			ID = ident;
			chromosomes = chromes;
			instantiation = parent;
			unitArray = new ArrayList ();
			
		}
		public bluePrint(string ident, string[] chromes)
		{
			score = 0;
			ID = ident;
			chromosomes = chromes;	
			unitArray = new ArrayList ();
		}
		public bluePrint(string Ident){
			score = 0;
			ID = Ident;
			unitArray = new ArrayList ();


	}
		public bool unitAreaOccupied(point3 p){

			foreach (functionalUnit a in unitArray) {
								if (a.location.x == p.x && a.location.y == p.y && a.location.z == p.z) {

										return true;
								}
						}
			return false;

				}
		public functionalUnit getUnit (string ident){
			foreach (functionalUnit a in unitArray) {
				if (a.ID == ident) {					
					return a;
				}
			}
			Debug.Log ("no functional unit with name: " + ident + " could be found.");
			return null;

		}
	
	}
}

