//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
namespace AssemblyCSharp
{
	public class functionalUnit
	{

		public string ID { get; set; }
		public GameObject instantiation{ get; set; }
		public point3 location;

		
		public functionalUnit(string ident, point3 mypoint)
		{
			location = mypoint;
			ID = ident;	

			
		}

	}
}


